<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="AdminAs-MBP-4.fios-router.home" name="runner.TestRunner" tests="4" failures="1" timestamp="02 Oct 2019 07:00:56 GMT" time="0.243" errors="0">
  <testcase name="runScenario" time="0.007" classname="runner.TestRunner">
    <failure type="java.lang.AssertionError" message="Summary of all values ($997000.0) doesn&#039;t match with expected Total Balance. expected [1000000.0] but found [997000.0]">
      <![CDATA[java.lang.AssertionError: Summary of all values ($997000.0) doesn't match with expected Total Balance. expected [1000000.0] but found [997000.0]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at steps.MyStepdefs.iVerifyThatTheTotalBalanceIsCorrectBasedOnTheValuesListedOnTheScreen(MyStepdefs.java:80)
at âœ½.I verify that the total balance is correct based on the values listed on the screen(src/test/resources/problem.feature:35)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="0.226" classname="runner.TestRunner"/>
  <testcase name="runScenario" time="0.005" classname="runner.TestRunner"/>
  <testcase name="runScenario" time="0.005" classname="runner.TestRunner"/>
</testsuite> <!-- runner.TestRunner -->
